#include "spinning.hpp"

#include <cerrno>
#include <cstring>
#include <fcntl.h>
#include <linux/input.h>
#include <sys/ioctl.h>
#include <unistd.h>

namespace {
// Linux input event codes. Android's InputReader translates these to the
// corresponding Android DPAD/arrow key events (KEYCODE_DPAD_LEFT/RIGHT).
constexpr int kLinuxKeyLeft = 105;   // KEY_LEFT
constexpr int kLinuxKeyRight = 106;  // KEY_RIGHT
constexpr int kEvKey = 0x01;         // EV_KEY
constexpr int kEvSyn = 0x00;         // EV_SYN
constexpr int kSynReport = 0x00;     // SYN_REPORT

// Keep this file self-contained so it does not depend on the presence of
// linux/uinput.h in the Android NDK sysroot.
struct UInputUserDev {
    char name[80];
    unsigned short id_bustype;
    unsigned short id_vendor;
    unsigned short id_product;
    unsigned short id_version;
    unsigned int ff_effects_max;
    signed int absmax[64];
    signed int absmin[64];
    signed int absfuzz[64];
    signed int absflat[64];
};

#ifndef UI_SET_EVBIT
#define UI_SET_EVBIT _IOW('U', 100, int)
#endif
#ifndef UI_SET_KEYBIT
#define UI_SET_KEYBIT _IOW('U', 101, int)
#endif
#ifndef UI_DEV_CREATE
#define UI_DEV_CREATE _IO('U', 1)
#endif
#ifndef UI_DEV_DESTROY
#define UI_DEV_DESTROY _IO('U', 2)
#endif
}

SpinningModule::SpinningModule()
    : Module("Spinning", "Holds the left or right arrow key until the module is disabled.") {}

SpinningModule::~SpinningModule() {
    destroyInputDevice();
}

void SpinningModule::onInit() {}

void SpinningModule::onEnable() {
    if (!m_leftSpinning && !m_rightSpinning) return;
    if (!createInputDevice()) return;
    syncKeys();
}

void SpinningModule::onDisable() {
    releaseKeys();
    destroyInputDevice();
}

void SpinningModule::onFrame() {
    if (!enabled) return;
    // Re-assert the desired state each frame. This also recovers from an
    // unexpected key release generated by another input layer.
    syncKeys();
}

bool SpinningModule::createInputDevice() {
    if (m_deviceReady && m_uinputFd >= 0) return true;

    m_uinputFd = open("/dev/uinput", O_WRONLY | O_NONBLOCK | O_CLOEXEC);
    if (m_uinputFd < 0) return false;

    if (ioctl(m_uinputFd, UI_SET_EVBIT, kEvKey) < 0 ||
        ioctl(m_uinputFd, UI_SET_KEYBIT, kLinuxKeyLeft) < 0 ||
        ioctl(m_uinputFd, UI_SET_KEYBIT, kLinuxKeyRight) < 0) {
        close(m_uinputFd);
        m_uinputFd = -1;
        return false;
    }

    UInputUserDev device{};
    std::strncpy(device.name, "BedrockTools Spinning", sizeof(device.name) - 1);
    device.id_bustype = 0x03; // BUS_USB
    device.id_vendor = 0xB7;
    device.id_product = 0x7001;
    device.id_version = 1;

    if (write(m_uinputFd, &device, sizeof(device)) != static_cast<ssize_t>(sizeof(device)) ||
        ioctl(m_uinputFd, UI_DEV_CREATE) < 0) {
        close(m_uinputFd);
        m_uinputFd = -1;
        return false;
    }

    m_deviceReady = true;
    m_leftDown = false;
    m_rightDown = false;
    return true;
}

void SpinningModule::destroyInputDevice() {
    releaseKeys();
    if (m_uinputFd >= 0) {
        if (m_deviceReady) ioctl(m_uinputFd, UI_DEV_DESTROY);
        close(m_uinputFd);
    }
    m_uinputFd = -1;
    m_deviceReady = false;
}

bool SpinningModule::emitKey(int code, bool down) {
    if (m_uinputFd < 0 || !m_deviceReady) return false;

    input_event event{};
    event.type = kEvKey;
    event.code = static_cast<__u16>(code);
    event.value = down ? 1 : 0;

    if (write(m_uinputFd, &event, sizeof(event)) != static_cast<ssize_t>(sizeof(event))) return false;

    input_event sync{};
    sync.type = kEvSyn;
    sync.code = kSynReport;
    sync.value = 0;
    return write(m_uinputFd, &sync, sizeof(sync)) == static_cast<ssize_t>(sizeof(sync));
}

void SpinningModule::syncKeys() {
    if (!m_leftSpinning && !m_rightSpinning) {
        releaseKeys();
        return;
    }
    if (!createInputDevice()) return;

    const bool wantLeft = keyLeftSelected(m_leftSpinning, m_rightSpinning);
    const bool wantRight = keyRightSelected(m_leftSpinning, m_rightSpinning);

    if (wantLeft != m_leftDown) {
        if (emitKey(kLinuxKeyLeft, wantLeft)) m_leftDown = wantLeft;
    }
    if (wantRight != m_rightDown) {
        if (emitKey(kLinuxKeyRight, wantRight)) m_rightDown = wantRight;
    }
}

void SpinningModule::releaseKeys() {
    if (m_uinputFd >= 0 && m_deviceReady) {
        if (m_leftDown) emitKey(kLinuxKeyLeft, false);
        if (m_rightDown) emitKey(kLinuxKeyRight, false);
    }
    m_leftDown = false;
    m_rightDown = false;
}

void SpinningModule::loadConfig(const nlohmann::json& j) {
    Module::loadConfig(j);

    bool left = m_leftSpinning;
    bool right = m_rightSpinning;
    if (j.contains("m_leftSpinning")) left = j["m_leftSpinning"].get<bool>();
    if (j.contains("m_rightSpinning")) right = j["m_rightSpinning"].get<bool>();

    // The launcher builds the updated JSON from the current module state,
    // then changes one field. When both are true, use the previous state to
    // determine which toggle the user just enabled and turn the other off.
    if (left && right) {
        if (!m_leftSpinning && m_rightSpinning) {
            left = false;
        } else if (m_leftSpinning && !m_rightSpinning) {
            right = false;
        } else {
            right = false;
        }
    }

    const bool changed = left != m_leftSpinning || right != m_rightSpinning;
    m_leftSpinning = left;
    m_rightSpinning = right;

    if (changed && enabled) {
        syncKeys();
    }
}

void SpinningModule::saveConfig(nlohmann::json& j) {
    Module::saveConfig(j);
    j["m_leftSpinning"] = m_leftSpinning;
    j["m_rightSpinning"] = m_rightSpinning;
}
